# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
workflows:
  version: 2
  talon_community:
    jobs:
      - build
      - lint:
          requires:
            - build

dockers:
  - &python_docker
    image: circleci/python:3.6.1

setup_steps:
  - &attach
    attach_workspace:
      at: /home/circleci

jobs:
  build:
    docker:
      - *python_docker
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  lint:
    docker:
      - *python_docker
    steps:
      - *attach
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8 --exclude venv
